name: Shadedcloud
favicon: null
layout_spectrum: 0.8509213251527399
typography_spectrum: 0.07747442834079266
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9978681495413184
  lightness: 0.505067375022918
  saturation: 0.6130266315303743
  rhythmicContrast: 0.9229176007211208
purpose: []
