name: Shadedcloud
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 1
  brandStrength: 0.7297872
  lightness: 0.5050673
  brandColors:
    - '#1F1F1F'
    - '#B3B4B4'
    - '#FB6502'
    - '#FFD702'
    - '#FF6577'
  rhythmicContrast: 0.3382979
typography_spectrum: 0.09148936
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
layout_spectrum: 1
